# Generated by Django 2.2.3 on 2019-07-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('estimated_time', models.IntegerField(default=1)),
                ('worked_time', models.FloatField(default=0.0)),
            ],
        ),
    ]
