# Generated by Django 2.2.3 on 2019-07-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='difference_time',
            field=models.IntegerField(default=1),
        ),
    ]
